### ISSUE TITLE
Missing metadata.csv

### ISSUE THREAD

**Issue by motey** [josephsdavid/cord-19-tools#6] opened 2020-04-22 18:42 UTC
Hey Thanks for the great toolset. i am using it for the covidgraph.org project.

with v0.3.2 and using the function `cotools.download()`
i am missing the metadata.csv file from the CORD-19 Dataset.

is it only me or do others having the same problem?
Or is this on purpose?

**Comment by josephsdavid** [comment] 2020-04-22 18:43
I’ll look into it!

**Comment by josephsdavid** [comment] 2020-04-22 19:01
The issue is semantic scholar keeps changing up the data structure just slightly, should have a solution for you in just a moment!

**Comment by josephsdavid** [comment] 2020-04-22 19:35
Please update to 0.3.3! Should be fixed! Changes detailed in [this commit](https://github.com/josephsdavid/cord-19-tools/commit/688365fd3d28b8af1ab0ffba880e0ed4f0d7cc16)

**Comment by josephsdavid** [comment] 2020-04-22 19:40
Also thanks for sharing! This knowledge graph looks really useful 😁

**Comment by josephsdavid** [comment] 2020-04-24 22:22
Closing this unless you are still having problems!

**Closed as completed by josephsdavid** 2020-04-24 22:22 UTC

**Comment by motey** [comment] 2020-04-25 09:23
Sorry, missed to give feedback.
Yep works again. Thanks a lot
